workflows:
  ios-workflow:
    name: IRONVAULT AI IPA Build

    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:

      - name: Install dependencies
        script: |
          npm install

      - name: Capacitor sync
        script: |
          chmod -R 755 node_modules
          npx cap sync ios

      - name: Build Archive
        script: |
          cd ios/App

          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $CM_BUILD_DIR \
            CODE_SIGNING_ALLOWED=NO

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/*.xcarchive